// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzWD33Ia87WEsdZ8T3OALyvgq6rdX2E8c',
    appId: '1:305742941727:web:474e28a534498807600f2a',
    messagingSenderId: '305742941727',
    projectId: 'clustrr-34290',
    authDomain: 'clustrr-34290.firebaseapp.com',
    storageBucket: 'clustrr-34290.firebasestorage.app',
    measurementId: 'G-VV4X58BDBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqm0JefXBQXZF5aIc_Uf1OlTGxXEOjs3g',
    appId: '1:305742941727:android:9d9bf070db721b72600f2a',
    messagingSenderId: '305742941727',
    projectId: 'clustrr-34290',
    storageBucket: 'clustrr-34290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaTLXEGJ_VUczmpb6eZDs67Ni6ofLb1lk',
    appId: '1:305742941727:ios:38203e66e9863a11600f2a',
    messagingSenderId: '305742941727',
    projectId: 'clustrr-34290',
    storageBucket: 'clustrr-34290.firebasestorage.app',
    iosClientId: '305742941727-4lfol3pda0ii55hde1jlr4sog2c0il10.apps.googleusercontent.com',
    iosBundleId: 'com.example.clustrr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaTLXEGJ_VUczmpb6eZDs67Ni6ofLb1lk',
    appId: '1:305742941727:ios:38203e66e9863a11600f2a',
    messagingSenderId: '305742941727',
    projectId: 'clustrr-34290',
    storageBucket: 'clustrr-34290.firebasestorage.app',
    iosClientId: '305742941727-4lfol3pda0ii55hde1jlr4sog2c0il10.apps.googleusercontent.com',
    iosBundleId: 'com.example.clustrr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzWD33Ia87WEsdZ8T3OALyvgq6rdX2E8c',
    appId: '1:305742941727:web:41af0018279e1172600f2a',
    messagingSenderId: '305742941727',
    projectId: 'clustrr-34290',
    authDomain: 'clustrr-34290.firebaseapp.com',
    storageBucket: 'clustrr-34290.firebasestorage.app',
    measurementId: 'G-KRYX6BW7P5',
  );

}